#pragma once
#define INTEGER "INTEGER"
#define EOF "EOF"
#define PLUS "PLUS"
#define MINUS "MINUS"
#define MUL "MUL"
#define DIV "DIV"
#define LPAREN "LPAREN"
#define RPAREN "RPAREN"
#define WORD "WORD"